image: docker:stable-git
variables:
  ROBOT_USER: $REGISTRY_USER
stages:
  - docker
  - harbor
  - deploy-server

build-front:
  stage: docker
  script:
    - docker build -t reg.amoyel.fr/aheroin/landingpage-front ./front
  only:
    - master

build-api:
  stage: docker
  script:
    - docker build -t reg.amoyel.fr/aheroin/landingpage-api ./api
  only:
    - master

push:
  stage: harbor
  variables:
    ROBOT_USER: $REGISTRY_USER
  before_script:
    - echo "registry user is :" $ROBOT_USER
  script:
    - echo "$REGISTRY_PASSWORD" | docker login reg.amoyel.fr -u "$ROBOT_USER" --password-stdin
    - docker push reg.amoyel.fr/aheroin/landingpage-front
    - docker push reg.amoyel.fr/aheroin/landingpage-api

docker-deploy:
  stage: deploy-server
  image: docker/compose
  tags:
    - deploy-server
  script:
    - docker-compose down --remove-orphans
    - docker-compose pull
    - docker-compose -f docker-compose-prod.yml up -d --force-recreate
  only:
    - master
