image: docker:stable-git

stages:
  - docker
  - deploy-server

build-front:
  stage: docker
  script:
    - echo "$REGISTRY_PASSWORD" | docker login reg.amoyel.fr -u "$REGISTRY_USER" --password-stdin
    - docker build -t reg.amoyel.fr/aheroin/landingpage-front ./front
    - docker push reg.amoyel.fr/aheroin/landingpage-front
  only:
    - master

build-api:
  stage: docker
  script:
    - echo "$REGISTRY_PASSWORD" | docker login reg.amoyel.fr -u "$REGISTRY_USER" --password-stdin
    - docker build -t reg.amoyel.fr/aheroin/landingpage-api ./api
    - docker push reg.amoyel.fr/aheroin/landingpage-api
  only:
    - master

docker-deploy:
  stage: deploy-server
  image: docker/compose
  tags:
    - deploy-server
  script:
    - docker-compose down --remove-orphans
    - docker-compose pull
    - docker-compose -f docker-compose-prod.yml up -d --force-recreate
  only:
    - master
