version: '3.1'
services:
  front:
    image: node:alpine
    container_name: landingpage-front
    working_dir: /var/www/front
    command: npm start
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./front:/var/www/front
      - /front/app/node_modules
    ports:
      - 81:3000
    expose:
      - 81
    depends_on:
      - api
    networks:
      - redis
  api:
    image: node:alpine
    container_name: landingpage-api
    expose:
      - 3001
    ports:
      - "3001:3001"
    volumes:
      - ./api:/var/www/api
      - /api/app/node_modules
    working_dir: /var/www/api
    command: npm run start:dev
    depends_on:
      - redis
    networks:
      - redis
  redis:
    image: bitnami/redis:latest
    container_name: landingpage-redis
    hostname: landingpage-redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - "./volumes/redis:/bitnami/redis/data"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis
networks:
  redis:
    driver: bridge
