version: '3'
services:
  front:
    image: reg.amoyel.fr/aheroin/landingpage-front:latest
    container_name: landingpage-front
    ports:
      - "81:80"
    links:
      - api
    restart: always
    networks:
      - redis

  api:
    image: reg.amoyel.fr/aheroin/landingpage-api:latest
    container_name: landingpage-api
    ports:
      - "3001:3001"
    restart: always
    networks:
      - redis

  redis:
    image: bitnami/redis:latest
    container_name: landingpage-redis
    hostname: landingpage-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - "./volumes/redis:/bitnami/redis/data"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - redis
networks:
  redis:
    driver: bridge
